### ISSUE TITLE
ContentfulSpeedIndex is not correct

### ISSUE THREAD

**Issue by sefeng211** [sitespeedio/browsertime#1178]
There's bug in how we use the [`matcher` regex](https://github.com/sitespeedio/browsertime/blob/master/browsertime/visualmetrics.py#L1680) I think.

Say the output of the `convert` command is `'534: (123,456,789) #FFFFFF gray(444)'`. In this case, we want the value to be `534` which is the pixel count I think, but the `matcher` regex would return `444` from it. See https://regex101.com/r/C1p0Pg/1. 

This also indicates the ContentfulSpeedIndex test is not correct or sufficient. 

We should fix it and it's not clear to me of why we complicate it with this regex, actually this entire line feels a bit overkill to me.

**Comment by tarekziade** [comment]
The reason I moved to a regex was because the previous version was trying to convert gray(444) to an int() and was raising an error. I thought 444 was the value we wanted in this line since the code was looking to extract the last value of the line. If we want the first value, yeah, the regex is overkill, we can just split and grab that

**Comment by sefeng211** [comment]
Not sure about the int error part, but I think the previous one was also trying to use `534`. 
The previous one  doesn't have the line split yet, so the `output` was the result from the command. 
Should be something like this. 
```
output = '76960: (  0,  0,  0) #000000 gray(0) 8640: (255,255,255) #FFFFFF gray(255)'
print(output.split()[7].split(':')[0])
>> 8640
```
If it was looking for gray(444), then we wouldn't need the `split(':')`.

**Comment by tarekziade** [comment]
well, that split() thing is fragile, that's what broke for me (and others) before on macOS. The test I added was breaking because the 7th element was gray(0) from your eexample. I think EOLs are a bit different for "convert" depending on the platform.

Do you have an EOL before 8640 ? In any case, i guess you just need to change the test with the test data that's already there, and add your own test data, then adapt the code so it works as expected. Once the patch is ready, we should try on all 3 platforms (I don't think travis/circle ci do this). If you don't use regexp, make sure you clean up the split list result from an space outputs (' ' ) and strip it.

**Comment by sefeng211** [comment]
I see...EOL is a possible explanation, however acreskey was on macOS as well, and I don't think he had an issues. Bizarre ╮(╯_╰)╭ 

Anyways, I'll do a patch on Monday

**Comment by tarekziade** [comment]
> however acreskey was on macOS as well, and I don't think he had an issues

you mean with the previous versions ? weird because afair that bug has been around for a while and @soulgalore added a try..except in that function to make sure its occurence did not breeeak the whole process. (see also the bugzilla bug referenced)

In any case, if the existing test pass (pending the tweak of the output value) we're good
