### ISSUE TITLE
Browsertime doesn't terminate the browser if Date.now() is overwritten to return the same value

### ISSUE THREAD

**Issue by gogo9th** [sitespeedio/browsertime#1228]
Hi, 

For my personal experimental reason, I had to overwrite Date.now() to return always the same value. But if I do this, browsertime doesn't stop the browser even after the pageload event is fired. I wonder how I could make browsertime automatically finish when the pageload is complete.  

Ronny

**Comment by soulgalore** [comment]
Hi @gogo9th what version are you using? I think since 8.0 we changed default pageComleteCheck to use `performance.now` instead of `Date.now()`, meaning it should work?

You can also choose yourself when to end your test, checkout https://www.sitespeed.io/documentation/sitespeed.io/browsers/#choose-when-to-end-your-test.

Best
Peter

**Comment by gogo9th** [comment]
Hi Peter,

Thanks for your comments. I think this works!
