### ISSUE TITLE
Why does SpeedIndex have second as their unit? 

### ISSUE THREAD

**Issue by sefeng211** [sitespeedio/browsertime#1320]
Looks like starting from this [commit](https://github.com/sitespeedio/browsertime/commit/296b78bd5713ef096e5643a8bab54167cd68cac7), `SpeedIndex` is interpreted as a time, this feels weird and incorrect.

**Comment by soulgalore** [comment]
Hi @sefeng211 
I think Speed Index always been ms/s see https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/metrics/speed-index but there was a move a year ago or something where all tools started to show it instead of having it unit-less, see for example https://github.com/GoogleChrome/lighthouse/issues/6130

**Comment by gmierz** [comment]
Hi @soulgalore, I find that using seconds as the unit is a bit misleading given that *SI metrics actually have units of `%complete * time` which is likely why lighthouse is showing them as unitless now.

I think the webpagetest documentation is also misleading since speed index is calculated as the area under a curve which is not a time value. I would agree that it approximates a temporal value, but it isn't exactly a temporal value:
```
The Speed Index is the average time at which visible parts of the page are displayed.  It is expressed in milliseconds...
```

**Comment by soulgalore** [comment]
Yep I see your point, but I think you are wrong how other tools show them, see the Lighthouse link I posted and the screenshot from LightHouse:

<img width="367" alt="Screenshot 2021-04-12 at 14 15 56" src="https://user-images.githubusercontent.com/540757/114392846-9f4f2d80-9b99-11eb-91c5-5903ad3fec39.png">

I don't changing though, can we have something better than it unitless?

**Comment by soulgalore** [comment]
This isn't perfect but maybe we can leave it as is for now.
