### ISSUE TITLE
browsertime forward to a error page

### ISSUE THREAD

**Issue by kakazuo** [sitespeedio/browsertime#153]
I am using sitespeed.io to test my website, it's installed on a ubuntu 14.04 LTS vm, but everytime I run test command, it always forwards to http://www.mozilla.org/en-US/firefox/new, for example, I run following command:
`sitespeed.io -u http://www.google.com -d 0 -b firefox`

**Comment by soulgalore** [comment]
Hi @kakazuo ,
thanks for reporting, I thought we configured FF to not auto-update but could be the configuration changed or something is wrong. Which sitespeed.io version and Firefox version are you running? 

Best
Peter

**Comment by kakazuo** [comment]
Hi, @soulgalore 

firefox: 47.0
OS: 'linux 3.13.0-88-generic'(Ubuntu LTS 14.04), Node.js: 'v4.4.5', sitespeed.io: '3.11.5', PhantomJS: '2.1.1', java: '1.7.0_101', browsertime: '0.12.2'

**Comment by soulgalore** [comment]
Hey @kakazuo aha! So there's a bug in Firefox 47 that makes it to fail with the Firefoxdriver in Selenium (see https://github.com/sitespeedio/sitespeed.io/issues/993 and the unresolved part https://www.mozilla.org/en-US/firefox/47.0/releasenotes/). On OS X the driver just stop, I guess then the behaviour on Ubuntu is different. It will be fixed in 47.0.1.

You can either downgrade to Firefox 46 (yes that sucks) or use our Docker container, that is built with the latest working browser version.

Best
Peter

**Comment by soulgalore** [comment]
Closing this, please re-open if you still have the problem.
