### ISSUE TITLE
Blacklist urls

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#156]
Blacklist and/or whitelist URLs. One way could be to do it in the [tsproxy](https://github.com/WPO-Foundation/tsproxy)?

**Comment by beenanner** [comment]
Is this for testing SPOFs?

**Comment by soulgalore** [comment]
thinking testing the speed with or without ads etc?

**Comment by worenga** [comment]
Did some research on this out of curiosity: 
- tsproxy is not really an option as this socks proxy only delays packages and has no state.
one would need an intercepting proxy such as mitmproxy. to do such thing. but i do not like the idea of using an http proxy and measuring sitespeed, because the userspace proxy influences the measurement quite a bit.
- if you google this you find a lot solution references to browsermobproxy, which we do not want either.

I think the best way is to do blacklisting on the browserlevel again by using an configurable ad-block extension.
I've seen this done with FF in OpenWPM ( https://github.com/citp/OpenWPM/blob/master/automation/DeployBrowsers/configure_firefox.py#L56 ) 
And i think selenium also allows one to add a chrome extension.
The tricky part would be to configure the browser extensions to block the urls accordingly.

**Comment by tobli** [comment]
This is included in 174dbe6.
