### ISSUE TITLE
Issues with portable script

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#1744]
Hi Greg, when did some test runs today I found some new things that I missed before or maybe got introduces not sure.

Using main branch running a test:
`❯ bin/browsertime.js --video --visualMetrics --visualMetricsPortable https://www.sitespeed.io -n 1` do not produce any video after the test, that is removed. My guess is that there's a check somewhere that somehow become broken with visualMetricsPortable, I can have look and fix that tonight.
<img width="659" alt="Screenshot 2022-03-30 at 11 29 31" src="https://user-images.githubusercontent.com/540757/160799793-2226fba9-46b0-447d-b8e7-70403ac18742.png">

Another thing is that the first visual change is wrong for me and I think the reason is that the first frame is an orange frame (you can see that in the screenshot too). Do you get the same when you test?

**Comment by gmierz** [comment]
Thanks for the ping, I'm looking into it.

One thing to note is that I had an issue trying to run browsertime. Here's the error I was getting:
```
sparky@sparky-ThinkPad-X1-Carbon-6th:~/mozilla-source/sitespeedio$ bin/browsertime.js --video --visualMetrics --visualMetricsPortable https://www.sitespeed.io -n 1
internal/util.js:260
    throw new ERR_INVALID_ARG_TYPE('original', 'Function', original);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type Function. Received type undefined
    at promisify (internal/util.js:260:11)
    at Object.<anonymous> (/home/sparky/mozilla-source/sitespeedio/lib/chrome/webdriver/chromium.js:19:12)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/sparky/mozilla-source/sitespeedio/lib/core/engine/index.js:11:18)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/sparky/mozilla-source/sitespeedio/index.js:3:16) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

I managed to get around it by using node version 16 but the package.json mentions the version needs to be >=10.

**Comment by soulgalore** [comment]
Let me fix that, it should always be latest LTS release of NodeJS.

**Comment by gmierz** [comment]
> Hi Greg, when did some test runs today I found some new things that I missed before or maybe got introduces not sure.
> 
> Using main branch running a test: `❯ bin/browsertime.js --video --visualMetrics --visualMetricsPortable https://www.sitespeed.io -n 1` do not produce any video after the test, that is removed. My guess is that there's a check somewhere that somehow become broken with visualMetricsPortable, I can have look and fix that tonight. <img alt="Screenshot 2022-03-30 at 11 29 31" width="659" src="https://user-images.githubusercontent.com/540757/160799793-2226fba9-46b0-447d-b8e7-70403ac18742.png">
> 

I can't reproduce this failure. I see the 1.mp4 file in the browsertime-resultls folder. Note that the path in the folder that was created for me is different from yours: `sitespeedio/browsertime-results/www.sitespeed.io/2022-03-30T073230-0400/pages/www_sitespeed_io/data/video/1.mp4`

Are you using python v3+ to run the visualmetrics-portable.py script? I've seen silent failures for this before (I think I should add a check for that).

> Another thing is that the first visual change is wrong for me and I think the reason is that the first frame is an orange frame (you can see that in the screenshot too). Do you get the same when you test?

Can you disable the `fineTuneVideo` method and see if you can get the video that was produced? Locally, I haven't seen any issues but that's because the videos being produced from the command you provided are bad:

https://user-images.githubusercontent.com/10966989/160828266-f4fa4e66-9c27-4ba9-ad3b-62f0e4fd57bf.mp4

I had to add `--xvfbParams.display 0` to get it working as well.

**Comment by soulgalore** [comment]
I could see that the video was produced (and then later removed) and I got visual metrics, but they where off. I'll have closer look tonight.

**Comment by gmierz** [comment]
Sounds good.

The `fineTuneVideo` method prevents us from being able to check if the values of the new script agree with the old script since it modifies the original video. I have a feeling that this is where that difference you are seeing is coming from. If you run the old, and new script on that exact video that was modified from the original, you should get the same values.

What I do when I want to verify the values is:
(1) Disable the fineTuneVideo method. Otherwise the values we get from browsertime will be the only time we can get those values (it'll be impossible to get the same value with the modified video).
(2) Get the video, run the following, and save the results JSON: `./browsertime/visualmetrics-portable.py --video /home/sparky/mozilla-source/sitespeedio/browsertime-results/www.sitespeed.io/2022-03-30T080425-0400/pages/www_sitespeed_io/data/video/1.mp4 --orange --force --renderignore 5 --json --viewport --viewportretries 60 --viewportminwidth 100 --viewportminheight 100 -vvvv`
(3) Run the following on the same video, and save the results JSON: `./browsertime/visualmetrics.py --video /home/sparky/mozilla-source/sitespeedio/browsertime-results/www.sitespeed.io/2022-03-30T080425-0400/pages/www_sitespeed_io/data/video/1.mp4 --orange --force --renderignore 5 --json --viewport --viewportretries 60 --viewportminwidth 100 --viewportminheight 100 -vvvv`
(4) Compare the results JSONs.

**Comment by soulgalore** [comment]
@gmierz sorry I think it could be something that is broken in my setup. When I tested on another machine it works just fine. I'm gonna try some more tonight.

There's a trick to store the original video, you can use `--videoParams.keepOriginalVideo` and then you will have the untouched video named _1-original.mp4_ in the video directory.

**Comment by gmierz** [comment]
Ah thank you! I completely missed that. :)

**Comment by soulgalore** [comment]
Problem solved. Somehow I missed installing numpy. If you add -vvvv to your run, the log file from visual metrics is kept after the test finished so that was how I found out.
```
09:18:35.004 - No module named 'numpy'
Traceback (most recent call last):
  File "/Users/peter/git/browsertime/browsertime/visualmetrics-portable.py", line 92, in crop_im
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

@gmierz is it possible to add checks that the new dependencies are installed before the run? Right now the script continues and surprisingly it produces metrics without numpy (but the metrics are wrong). I'm thinking in the long run we want to move over to the new script and then its super if it breaks if we miss the new dependencies.

**Comment by gmierz** [comment]
@soulgalore sure! There's a couple ways I could go about fixing this but to keep the workflow similar to the previous script, I'll add a call to check the requirements before running (even if --check isn't provided).

**Comment by gmierz** [comment]
See PR #1749 for the issue related to requirements.

**Comment by soulgalore** [comment]
Thanks @gmierz ! I've pushed the new portable script so it runs for all tests on dashboard.sitespeed.io and I went through the metrics and it looks great! I've been checking the fastest of X runs for first visual change to make sure we don't pickup something too early (that happened before in old versions of the script) but it looks good!
