### ISSUE TITLE
Chrome 56 video includes orange frames

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#284]
Something has changed between Chrome 55 and 56:
First on Mac OS X running the Docker container you need to add the no-sandbox parameter (_ENV BROWSERTIME_CHROME__ARGS no-sandbox_).

But more important, the video now includes orange frames. I think the VisualMetrics is still correct since https://github.com/WPO-Foundation/visualmetrics/ handles it but we cut the video outside and something is wrong. 

In 55 and earlier Chrome versions:
1. We change the background to orange
2. We start the recording
3. We change the background to white
4. We tell the browser to navigate to the URL
5. The background stays white until the page changes that.

In 56:
1. We change the background to orange
2. We start the recording
3. We change the background to white
4. We tell the browser to navigate to the URL
5. After a while the browser changes back the background to orange (!)
6. The background stays orange until the page changes that.

Easiet way to test it to upgrade the Docker container to use _FROM sitespeedio/webbrowsers:firefox-51.0-chrome-56.0_ and add _ENV BROWSERTIME_CHROME__ARGS no-sandbox_ and then run:

<pre>
docker run --privileged --shm-size=1g --rm -v "$(pwd)":/browsertime-results sitespeedio/browsertime -n 1 -c cable --video --speedIndex https://en.wikipedia.org/wiki/Main_Page
</pre>

and look at the video.

**Comment by worenga** [comment]
I came across this to (remember the userstudy i posted in slack a few days ago?) we used chrome 57 master. 

When we did the first batch of recordings we used tsproxy for traffic shaping. and we experienced the orange bar in the recordings as well. 
However, when configuring traffic shaping manually outside of browsertime (using netem/tc) we did not experience any orange frames (yet). Maybe it is realted to this. Also maybe it has been already fixed in newer chrome versions.

**Comment by soulgalore** [comment]
I get it without traffic shaping, so I don't think it' related. Let me try with a new Chrome version tonight.

**Comment by soulgalore** [comment]
@worenga thanks, did a quick test in 57 beta and there it works!

**Comment by soulgalore** [comment]
57 stable is released and working fine.
