### ISSUE TITLE
TTFB & Total Bytes

### ISSUE THREAD

**Issue by Jacfem** [sitespeedio/browsertime#356]
Firstly, I love this tool! Thank you for actively maintaining it. Apologies if I've overlooked something, but it seems the only way to track TTFB or Total Bytes is through Sitespeed, and Browsertime doesn't track this on its own. 

This would be really useful, especially given that SEO is impacted by TTFB.

Let me know how I can help, or if anything is unclear. Thanks!

**Comment by soulgalore** [comment]
Hi @Jacfem thanks for the kind words :)

Browsertime collect all the original metrics that we use in sitespeed.io but then we re-package some of them. 

To get TTFB we use the Navigation Timing API and in the JSON output from Browsertime, the part that is TTFB is called BackendTime (we used that because that was what GA called it back in the days, maybe they changed name, I don't know because I don't use it).

Total Bytes: Browsertime collect the bytes for each response and adds it in the HAR file. Then we internally use [PageXray](https://github.com/sitespeedio/pagexray) to convert the HAR to a more readable JSON (there we calculate the total bytes etc), so if you use Browsertime standalone, you can do the same to get the same type of metrics (there's gonna be a big release of PageXray soonish, we have some changes that has been done but not released yet.

Let me know if that helped you, or if I can explain better! 

Best
Peter

**Comment by Jacfem** [comment]
@soulgalore Ok great, that makes sense & thanks for the quick response! I'll check out BackendTime.

As for what PageXray considers total bytes, it looks like pagexray.pageSummary.contentSize could be what I'm looking for (rather than the individual css/js/etc metrics)? If not, I'll keep an eye out for the bigger release coming up. 

Thank you!

**Comment by soulgalore** [comment]
Cool! If you just use PageXray you can get it with contentSize (the size of all responses when it been unpacked) and transferSize (that is the size sent over the wire.
