### ISSUE TITLE
Firefox profile path

### ISSUE THREAD

**Issue by mrajiullah** [sitespeedio/browsertime#391]
Is there any way currently available in the browser time to include firefox profile directory path?

**Comment by soulgalore** [comment]
Hi @mrajiullah no I don't think so, what do you need to do? You can add preferences to the newly created profilethat Browsertime creates with  **--firefox.preference** .

Best
Peter

**Comment by mrajiullah** [comment]
There are pages that appears different/customized when the users are logged in. For example I would like to visit a company's Facebook page using browser time but in a logged in mode. This would require   firefox to have relevant access information in the profile directory. I am not sure this can be achieved using preference.

**Comment by soulgalore** [comment]
Hi @mrajiullah ah I see. You could use a *--preScript* to log in the user first (a Selenium script), not 100% sure that it works in the current version of Firefox (it works in Chrome). There was a bug in Geckodriver that made it not work, it was fixed in the latest, but we haven't upgraded since Firefox 55 exporting HAR is broken, and we are waiting on 57 to be released (14th of November) with hopefully a new version of the HAR exporter.

**Comment by mrajiullah** [comment]
Does it work now, it doesn't work with Firefox 56

**Comment by soulgalore** [comment]
We haven't pushed any way to create a new profile, we have a lot of special settings to make measurements stable so not sure it is the way. The HAR plugin isn't released yet by Mozilla.

**Comment by mrajiullah** [comment]
And is there any way to input cookies from previous visit to any page? The pages look very different if they were visited before.

**Comment by soulgalore** [comment]
Right now you need to do it outside of the project so that kind of sucks. I would look into the selenium script and try to work around the error.

**Comment by mrajiullah** [comment]
Any script suggestion will be very helpful, thanks.

**Comment by mrajiullah** [comment]
Thanks!
