### ISSUE TITLE
Remove RUM SpeedIndex and Resource Timings (per default) for 3.0

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#438]
In the next major release I want to change two things in the default scripts:

1. I want us to remove RUM SpeedIndex because we have video Speed Index and it is superior and I think the RUM version doesn't add any value.
2. I want to remove that we default get resource timings because of the browsertime.json becomes unreadable if your site got more than 10 assets. 

Another approach could be that we push them behind a CLI param so we need to activate them by default. @tobli @beenanner what do you think?

**Comment by beenanner** [comment]
Agree with both and keeping the default simple and clean. Both options seem to be advance and should be hidden behind enable flags. #1 with the video and a docker setup I find this option not useful at all anymore. #2 seems more useful in my experience and putting that behind a param, so that it can be enabled if need be seems appropriate

**Comment by soulgalore** [comment]
We removed RT but kept RUMSpeedIndex.
