### ISSUE TITLE
Not collecting console log since version 3.9.0

### ISSUE THREAD

**Issue by nbluis** [sitespeedio/browsertime#748]
Hello everyone.

I've been proving some features of sitespeed and would like to be able to detect if pages are having javascript errors.

but from what I was able to verify this is a feature that worked until a certain moment but is no longer working in the newer versions.

investigating a little more I was able to identify the collection of logs no longer works since version 3.9.0 of browsertime. (until version 3.8.2 worked). This version has been updated from Chrome to version 70.

The problem is simple to reproduce:

- **3.8.2**
`docker run --rm -v "$(pwd)":/browsertime sitespeedio/browsertime:3.8.2 https://jsfiddle.net/1nf7hgL9/ -n 1  -b chrome --chrome.collectConsoleLog`
**Result: Actual console file.**
`[{"level":"SEVERE","message":"https://fiddle.jshell.net/1nf7hgL9/show/ 32:0 Uncaught ReferenceError: justThrowAnyError_InThisCaseNotDefinedFunction is not defined","timestamp":1549057875371,"type":""}]`

- **3.9.0**
`docker run --rm -v "$(pwd)":/browsertime sitespeedio/browsertime:latest https://jsfiddle.net/1nf7hgL9/ -n 1  -b chrome --chrome.collectConsoleLog`
**Result: Actual console file.**
`[]` - Empty array

- **Latest**
`docker run --rm -v "$(pwd)":/browsertime sitespeedio/browsertime:latest https://jsfiddle.net/1nf7hgL9/ -n 1  -b chrome --chrome.collectConsoleLog`
**Result: Theres no log file**

**Comment by soulgalore** [comment]
Hi @nbluis yep I could reproduce with latest 4.1. 

I  wonder if something changed internally in Chrome/Chromedriver then, I've checked with a site I know always adds things to the log and there it worked:
`docker run --rm -v "$(pwd)":/browsertime sitespeedio/browsertime:4.1.0  https://www.aftonbladet.se -n 1 -b chrome --chrome.collectConsoleLog`

And it looks like this:
`[{"level":"INFO","message":"https://www.aftonbladet.se/hyper-assets/preload.8aaf80efb0b2c71d138c.js 3:22215 \"AST library loaded: 0.16.1\"","timestamp":1549097549399,"type":""},{"level":"SEVERE","message":"https://id.aftonbladet.se/session?client_sdrn=sdrn%3Aschibsted.com%3Aclient%3A4f1692bb9daf7cd367000001&redirect_uri=https%3A%2F%2Flogin.aftonbladet.se%2Fv2%2Fauth - Failed to load resource: the server responded with a status of 400 ()","timestamp":1549097551465,"type":""},{"level":"WARNING","message":"https://cdn.svp.schibsted.io/player/3.7.3/player.next.min.js 0:117533 \"SVP Player SKD deprecation warning. Due to changes in browser policies, player will detect itself if it can autoplay.\"","timestamp":1549097552249,"type":""},{"level":"WARNING","message":"https://cdn.svp.schibsted.io/player/3.7.3/player.next.min.js 0:117533 \"SVP Player SKD deprecation warning. Due to changes in browser policies, player will detect itself if it can autoplay.\"","timestamp":1549097553245,"type":""},{"level":"SEVERE","message":"chrome-extension://invalid/ - Failed to load resource: net::ERR_FAILED","timestamp":1549097553530,"type":""},{"level":"WARNING","message":"https://www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js 56 document.registerElement is deprecated and will be removed in M73, around March 2019. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 for more details.","timestamp":1549097553552,"type":""},{"level":"WARNING","message":"https://www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js 51 Element.createShadowRoot is deprecated and will be removed in M73, around March 2019. Please use Element.attachShadow instead. See https://www.chromestatus.com/features/4507242028072960 for more details.","timestamp":1549097553556,"type":""},{"level":"SEVERE","message":"chrome-extension://invalid/ - Failed to load resource: net::ERR_FAILED","timestamp":1549097553558,"type":""}]`

Best
Peter
